export const actionTypes = {
  FETCHING_START: "FETCHING_START",
  FETCHING_SUCCESS: "FETCHING_SUCCESS",
  FETCHING_ERROR: "FETCHING_ERROR",
  SINGLE_USER: "SINGLE_USER",
  SORT_BY_NAME: "SORT_BY_NAME",
  SORT_BY_EMAIL: "SORT_BY_EMAIL",
  SORT_BY_COMPANY: "SORT_BY_COMPANY",
};
